"""empty message

Revision ID: 12d027323b92
Revises: a2000816cf92
Create Date: 2021-12-03 19:27:31.915533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12d027323b92'
down_revision = 'a2000816cf92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_email_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    # ### end Alembic commands ###
