"""empty message

Revision ID: 24e20fd71570
Revises: 8d9dfb1df2c1
Create Date: 2021-11-30 01:29:42.874171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e20fd71570'
down_revision = '8d9dfb1df2c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('client_name', sa.String(length=120), nullable=True))
    op.add_column('request', sa.Column('client_phone', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'client_phone')
    op.drop_column('request', 'client_name')
    # ### end Alembic commands ###
