"""empty message

Revision ID: a8329792b949
Revises: 2807edd385a2
Create Date: 2021-11-23 16:27:35.994853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8329792b949'
down_revision = '2807edd385a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.String(length=120), nullable=True),
    sa.Column('service', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('trucker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=80), nullable=True),
    sa.Column('vehicle_model', sa.String(length=80), nullable=True),
    sa.Column('vehicle_make', sa.String(length=80), nullable=True),
    sa.Column('vehicle_year', sa.String(length=80), nullable=True),
    sa.Column('vehicle_color', sa.String(length=80), nullable=True),
    sa.Column('vehicle_plate', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('full_name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('rating', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('user_type', sa.String(length=120), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('user', 'user_type')
    op.drop_column('user', 'rating')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'full_name')
    op.drop_table('vehicle')
    op.drop_table('request')
    # ### end Alembic commands ###
