"""empty message

Revision ID: be60bf7f515b
Revises: 
Create Date: 2021-12-02 18:16:20.745569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be60bf7f515b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=120), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('rating', sa.String(length=120), nullable=True),
    sa.Column('zip_code', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.String(length=120), nullable=True),
    sa.Column('service', sa.String(length=120), nullable=True),
    sa.Column('vehicle', sa.String(length=450), nullable=True),
    sa.Column('completed', sa.String(length=120), nullable=True),
    sa.Column('trucker_id', sa.String(length=120), nullable=True),
    sa.Column('client_name', sa.String(length=120), nullable=True),
    sa.Column('client_phone', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=80), nullable=True),
    sa.Column('vehicle_model', sa.String(length=80), nullable=True),
    sa.Column('vehicle_make', sa.String(length=80), nullable=True),
    sa.Column('vehicle_year', sa.String(length=80), nullable=True),
    sa.Column('vehicle_color', sa.String(length=80), nullable=True),
    sa.Column('vehicle_plate', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    op.drop_table('request')
    op.drop_table('user')
    # ### end Alembic commands ###
