"""empty message

Revision ID: e85ebba547c2
Revises: 758976fa7fd3
Create Date: 2021-11-30 00:46:53.145776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e85ebba547c2'
down_revision = '758976fa7fd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('vehicle_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'request', 'vehicle', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_column('request', 'vehicle_id')
    # ### end Alembic commands ###
